run:
  timeout: 4m

linters:
  disable-all: false
  enable:
    - gocyclo
    - misspell
    - nilerr
    - unparam
    - gosec
    - unused
    - govet
    - gosimple
    - errorlint
    - errcheck
    - dupl
    - dogsled
    - cyclop
    - exhaustive
    - funlen
    - gocognit
    - nestif
    - goconst
    - gocritic
    - godot
    - gofmt
    - revive
    - lll
    - makezero
    - nakedret
    - prealloc
    - nolintlint
    - staticcheck
    - thelper
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20

  misspell:
    locale: US

  unused:
    go: "1.19"

  unparam:
    check-exported: true

  govet:
    check-shadowing: false

  gosimple:
    go: "1.19"
    checks: ["all"]

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  dupl:
    threshold: 100

  dogsled:
    max-blank-identifiers: 2

  cyclop:
    max-complexity: 20
    package-average: 0.0
    skip-tests: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  funlen:
    lines: 95
    statements: 50

  gocognit:
    min-complexity: 35

  nestif:
    min-complexity: 10

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-checks:
      - unnamedresult
      - truncatecmp
      - ruleguard
      - nestingreduce
    enabled-tags:
      - performance
    disabled-tags:
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      elseif:
        skipBalanced: true
      hugeParam:
        sizeThreshold: 80
      nestingReduce:
        bodyWidth: 5
      rangeExprCopy:
        sizeThreshold: 512
        skipTestFuncs: true
      rangeValCopy:
        sizeThreshold: 32
        skipTestFuncs: true
      ruleguard:
        rules: ""
      truncateCmp:
        skipArchDependent: true
      underef:
        skipRecvDeref: true
      unnamedResult:
        checkExported: true

  godot:
    scope: declarations
    capital: false

  gofmt:
    simplify: true

  revive:
    ignore-generated-header: true
    severity: warning

  lll:
    line-length: 150
    tab-width: 1

  makezero:
    always: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  nolintlint:
    allow-unused: false
    allow-leading-space: true
    allow-no-explanation: []
    require-explanation: true
    require-specific: true

  staticcheck:
    go: "1.19"
    checks: ["all"]

  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true
    tb:
      first: true
      name: true
      begin: true

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - gocognit
        - unparam
        - lll
        - goconst
        - dupl
    - path: pkce-cli/
      linters:
        - lll
        - gocritic
    - path: shared/
      linters:
        - lll
    - path: api/
      linters:
        - funlen
        - gocritic
    - path: options/
      linters:
        - godot
        - gosec
    - path: optest/
      text: "hugeParam: user is heavy"
      linters:
        - gocritic
