name: Benchmark

on: pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Checkout Code (Previous)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: previous

      - name: Checkout Code (New)
        uses: actions/checkout@v3
        with:
          path: new

      - name: Install Dependencies
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run Benchmark (Previous)
        run: |
          cd previous
          make bench

      - name: Run Benchmark (New)
        run: |
          cd new
          make bench

      - name: Run Benchstat
        run: |
          benchstat previous/tmp/bench.txt new/tmp/bench.txt
