name: Benchmark go versions

on: pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Previous)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: previous

      - name: Checkout Code (New)
        uses: actions/checkout@v3
        with:
          path: new

      - name: Set up Go 1.17 for previous
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Run Benchmark (Previous)
        run: |
          cd previous
          make bench

      - name: Set up Go 1.18 for new
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Run Benchmark (New)
        run: |
          cd new
          make bench

      - name: Install Dependencies
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run Benchstat
        run: |
          benchstat previous/tmp/bench.txt new/tmp/bench.txt