name: Coverage main

on:
  push:
    branches:
      - main

jobs:
  coverage-main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"
      - name: coverage
        env:
          CI: true
        run: |
          make cover
      - name: Send coverage to coverall
        uses: shogo82148/actions-goveralls@v1.8.0
        with:
          path-to-profile: coverage_merged.out
          ignore: internal/oidctesting
